# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()

d1 =np.array(([1,2,3,4,5]))
# Create a 2-dimensional NumPy array using np.array()
d2 = np.array(([1,2,3,4,5], [1,2,3,4,5]))

# Create a 3-dimensional Numpy array using np.array()
d3 = np.array(([1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
d1.shape, d1.dtype, d1.size, type(d1)

((5,), dtype('int64'), 5, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
d2.shape, d2.dtype, d2.size, type(d2)

((2, 5), dtype('int64'), 10, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
d3.shape, d3.ndim, d3.dtype, d3.size, type(d3)

((3, 5), 2, dtype('int64'), 15, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(d2)

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones.shape

(10, 2)

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros.shape

(7, 2, 3)

In [9]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10,(7,2))

array([[3, 4],
       [6, 7],
       [1, 7],
       [3, 0],
       [3, 7],
       [1, 6],
       [9, 3]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.rand(3,5)

array([[0.6482582 , 0.58073221, 0.180744  , 0.56386458, 0.75879451],
       [0.85061249, 0.64717308, 0.35634831, 0.02700755, 0.22770517],
       [0.29745879, 0.48281233, 0.07576943, 0.79625555, 0.29705146]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10,(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [16]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
x = np.random.randint(1,10,(3,7))

# Find the unique numbers in the array you just created
np.unique(x)

array([1, 2, 3, 5, 6, 7, 8, 9])

In [17]:
# Find the 0'th index of the latest array you created
x[0]

array([9, 7, 9, 8, 2, 1, 7])

In [18]:
# Get the first 2 rows of latest array you created
x[:2,]

array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3]])

In [43]:
# Get the first 2 values of the first 2 rows of the latest array
x[:2][:,:2]

array([[9, 7],
       [7, 8]])

In [55]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
x = np.random.randint(1,10,(3,5))
ones = np.ones((3,5))

print(x)
print(ones)

[[3 2 5 6 7]
 [4 7 8 1 6]
 [8 5 4 2 6]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [48]:
# Add the two arrays together
x+ones

array([[ 7.,  9., 10.,  6.,  2.],
       [ 4.,  9.,  7.,  9., 10.],
       [ 5.,  2.,  2.,  5.,  8.]])

In [49]:
# Create another array of ones of shape (5, 3)
ones2 = np.ones((5,3))

In [51]:
# Try add the array of ones and the other most recent array together
ones+ones2.T

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [52]:
x

array([[6, 8, 9, 5, 1],
       [3, 8, 6, 8, 9],
       [4, 1, 1, 4, 7]])

In [56]:
y = np.random.randint(2,5,(3,5))

In [57]:
print(x)
print(y)

[[3 2 5 6 7]
 [4 7 8 1 6]
 [8 5 4 2 6]]
[[3 4 4 2 2]
 [4 3 2 4 4]
 [4 3 4 4 4]]


In [58]:
x>y

array([[False, False,  True,  True,  True],
       [False,  True,  True, False,  True],
       [ True,  True, False, False,  True]])

In [59]:
x==y

array([[ True, False, False, False, False],
       [ True, False, False, False, False],
       [False, False,  True, False, False]])